import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { CanvasSdkClient } from "../../sdk/src/index";
import WalletButton from "../components/WalletButton/WalletButton";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { Wallet } from "@project-serum/anchor";
import axios from "axios";

interface ICanvasData {
  name: string | undefined;
  slots?: [object];
}

const Home: NextPage = () => {
  const { connection } = useConnection();
  const wallet = useWallet();

  const [canvasModelName, setCanvasModelName] = useState("");

  const createCanvas = async (e) => {
    if (!wallet) {
      return false;
    }
    const response = await axios({
      method: "post",
      url: "/api/canvas",
      data: {
        canvasModelName,
      },
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>NFTCanvas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <WalletButton />
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to NFT Canvas UI</h1>

        <p className={styles.description}>
          <code className={styles.code}>Composable NFT&apos;s</code> for
          everyone 🤝
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Create Canvas &rarr;</h2>
            <p>Generate a new canvas model & slots</p>
          </a>
          <input
            value={canvasModelName}
            onChange={(e) => setCanvasModelName(e.target.value)}
          />
          <button onClick={createCanvas} type="button">
            Create Canvas
          </button>
        </div>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Create Canvas &rarr;</h2>
            <p>Generate a new canvas model & slots</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Placeholder &rarr;</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod.
            </p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Placeholder &rarr;</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod.
            </p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Placeholder &rarr;</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="http://www.nftcanvas.dev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>NFTCanvas</span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
